steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    echo "단순 문구 출력"
    echo "-------------"
    echo "스크립트 파일 실행"
    bash ./test.bash